# Generated by Django 4.2.4 on 2023-08-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='change_type',
            field=models.CharField(choices=[('Place', 'Place'), ('Move', 'Move'), ('Raise', 'Raise'), ('Lower', 'Lower'), ('Swap', 'Swap'), ('Remove', 'Remove'), ('List requirement', 'List requirement')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='change',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='change',
            name='effect',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
