# Generated by Django 4.2.4 on 2023-08-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0008_remove_level_objectcount'),
        ('change', '0002_change_change_type_alter_change_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='change_type',
            field=models.CharField(choices=[('Place', 'Place'), ('Move', 'Move'), ('Raise', 'Raise'), ('Lower', 'Lower'), ('Remove', 'Remove'), ('List requirement', 'List requirement')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='change',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='level.level'),
        ),
    ]
