# Generated by Django 4.2.4 on 2023-08-28 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0008_remove_level_objectcount'),
        ('change', '0003_alter_change_change_type_alter_change_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.level'),
        ),
    ]
