# Generated by Django 4.2.4 on 2023-08-28 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0008_remove_level_objectcount'),
        ('change', '0004_alter_change_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='above_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='above_level', to='level.level'),
        ),
        migrations.AlterField(
            model_name='change',
            name='below_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='below_level', to='level.level'),
        ),
        migrations.AlterField(
            model_name='change',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='level.level'),
        ),
    ]
