# Generated by Django 4.2.4 on 2023-08-28 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('level', '0009_alter_level_first_victor'),
        ('levelrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelrecord',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='level.level'),
        ),
        migrations.AlterField(
            model_name='levelrecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.player'),
        ),
    ]
