# Generated by Django 4.2.4 on 2023-08-28 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='region.region'),
        ),
    ]
