# Generated by Django 4.2.4 on 2023-08-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='creator',
            new_name='publisher',
        ),
    ]
