# Generated by Django 4.2.4 on 2023-08-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_rename_creator_level_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='contestants',
        ),
    ]
