# Generated by Django 4.2.4 on 2023-08-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_remove_level_contestants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='ranking',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
