# Generated by Django 4.2.4 on 2023-08-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_alter_level_ranking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='level',
            name='ranking',
        ),
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
