# Generated by Django 4.2.4 on 2023-08-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0005_alter_level_options_remove_level_ranking_level_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
    ]
