# Generated by Django 4.2.4 on 2023-08-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0006_alter_level_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='order',
            new_name='ranking',
        ),
    ]
