# Generated by Django 4.2.4 on 2023-08-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0007_rename_order_level_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='objectcount',
        ),
    ]
