# Generated by Django 4.2.4 on 2023-08-28 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('level', '0008_remove_level_objectcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='first_victor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='player.player'),
        ),
    ]
