# Generated by Django 4.2.4 on 2023-08-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '0009_alter_level_first_victor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('change_type', models.CharField(choices=[('Place', 'Place'), ('Move', 'Move'), ('Raise', 'Raise'), ('Lower', 'Lower'), ('Remove', 'Remove'), ('List requirement', 'List requirement')], default=None, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('effect', models.CharField(blank=True, max_length=255)),
                ('above_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='above_level', to='level.level')),
                ('below_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='below_level', to='level.level')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='level.level')),
            ],
        ),
    ]
