# Generated by Django 4.2.4 on 2023-08-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0009_alter_level_first_victor'),
        ('listchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Change',
            new_name='ListChange',
        ),
    ]
